M48
; DRILL file {KiCad 9.0.9} date 2026-09-28T04:16:47+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T04:16:47+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X118.46Y-72.0
X123.54Y-70.984
X123.54Y-73.016
T2
X109.0Y-51.0
X133.0Y-51.0
M30
